#
# Application
#

liferay.customer.version.picklists.api=${LIFERAY_CUSTOMER_VERSION_PICKLIST_API}
liferay.customer.version.picklists.dxp.major.erc=${LIFERAY_CUSTOMER_VERSION_PICKLIST_DXP_MAJOR_ERC}
liferay.customer.version.picklists.dxp.minor.erc=${LIFERAY_CUSTOMER_VERSION_PICKLIST_DXP_MINOR_ERC}
liferay.customer.version.picklists.dxp.minor.portal.major.erc=${LIFERAY_CUSTOMER_VERSION_PICKLIST_DXP_MINOR_PORTAL_MAJOR_ERC}
liferay.customer.version.picklists.portal.major.erc=${LIFERAY_CUSTOMER_VERSION_PICKLIST_PORTAL_MAJOR_ERC}
liferay.customer.version.picklists.portal.minor.erc=${LIFERAY_CUSTOMER_VERSION_PICKLIST_PORTAL_MINOR_ERC}
liferay.customer.version.picklists.releases.url=${LIFERAY_CUSTOMER_VERSION_PICKLIST_RELEASES_URL}

#
# OAuth
#

liferay.oauth.application.external.reference.codes=\
    liferay-customer-etc-cron-weekly-oahs