#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay-partner-etc-spring-boot-oauth-application-headless-server.oauth2.headless.server.client.secret=myfancypassword

liferay.oauth.application.external.reference.codes=\
    liferay-partner-etc-spring-boot-oauth-application-headless-server,\
    liferay-partner-etc-spring-boot-oauth-application-user-agent

liferay.oauth.urls.excludes=/ready

#
# SalesForce Object Entry Manager
#

liferay.partner.cloud.functions.base.url=${SPRING_CLOUD_FUNCTIONS_BASE_URL}
liferay.partner.cloud.functions.leadproxy.endpoint=${SPRING_CLOUD_FUNCTIONS_LEAD}
liferay.partner.cloud.functions.opportunitypartnerroleproxy.endpoint=${SPRING_CLOUD_FUNCTIONS_OPR}

liferay.partner.gcp.service.account.key.auth-provider-x509-cert-url=${SPRING_GCP_SA_KEY_AUTH_PROVIDER_URL}
liferay.partner.gcp.service.account.key.auth-uri=${SPRING_GCP_SA_KEY_AUTH_URI}
liferay.partner.gcp.service.account.key.client-x509-cert-url=${SPRING_GCP_SA_KEY_CLIENT_URL}
liferay.partner.gcp.service.account.key.client-id=${SPRING_GCP_SA_KEY_CLIENT_ID}
liferay.partner.gcp.service.account.key.client-email=${SPRING_GCP_SA_KEY_CLIENT_EMAIL}
liferay.partner.gcp.service.account.key.private-key=${SPRING_GCP_SA_KEY_PRIVATE_KEY}
liferay.partner.gcp.service.account.key.private-key-id=${SPRING_GCP_SA_KEY_PRIVATE_KEY_ID}
liferay.partner.gcp.service.account.key.project-id=${SPRING_GCP_SA_KEY_PROJECT_ID}
liferay.partner.gcp.service.account.key.token-uri=${SPRING_GCP_SA_KEY_TOKEN_URI}
liferay.partner.gcp.service.account.key.type=${SPRING_GCP_SA_KEY_TYPE}
liferay.partner.gcp.service.account.key.universe-domain=${SPRING_GCP_SA_KEY_UNIVERSE_DOMAIN}
#
# Spring Boot
#

server.port=58081
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.listener.simple.acknowledge-mode=${SPRING_RABBITMQ_ACK_MODE}
spring.rabbitmq.listener.simple.default-requeue-rejected=${SPRING_RABBITMQ_REQUEUE_REJECTED}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.requested-heartbeat=${SPRING_RABBITMQ_REQUESTED_HEARTBEAT}
spring.rabbitmq.ssl.enabled=${SPRING_RABBITMQ_SSL_ENABLED}
spring.rabbitmq.template.default-receive-queue=${SPRING_RABBITMQ_QUEUE}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}