#
# Spring Boot
#

spring.config.import=\
    classpath:/application-default.properties,\
    optional:configtree:${LIFERAY_ROUTES_CLIENT_EXTENSION}/,\
    optional:configtree:${LIFERAY_ROUTES_DXP}/
server.port=${SERVER_PORT}
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.listener.simple.acknowledge-mode=${SPRING_RABBITMQ_LISTENER_SIMPLE_ACKNOWLEDGE_MODE}
spring.rabbitmq.listener.simple.default-requeue-rejected=${SPRING_RABBITMQ_LISTENER_SIMPLE_DEFAULT_REQUEUE_REJECTED}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.requested-heartbeat=${SPRING_RABBITMQ_REQUESTED_HEARTBEAT}
spring.rabbitmq.ssl.enabled=${SPRING_RABBITMQ_SSL_ENABLED}
spring.rabbitmq.template.default-exchange=${SPRING_RABBITMQ_TEMPLATE_DEFAULT_EXCHANGE}
spring.rabbitmq.template.default-receive-queue=${SPRING_RABBITMQ_TEMPLATE_DEFAULT_RECEIVE_QUEUE}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}