#
# OAuth
#

liferay.oauth.application.external.reference.codes=liferay-partner-etc-spring-boot-oauth-application-headless-server
liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

spring.rabbitmq.template.default-exchange=my_exchange
spring.rabbitmq.template.default-receive-queue=my_queue