#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay.oauth.application.external.reference.codes=liferay-partner-etc-spring-boot-oauth-application-headless-server
liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081

#
# Koroneiki
#

koroneiki.subscriber.rabbitmq.host=
koroneiki.subscriber.rabbitmq.password=
koroneiki.subscriber.rabbitmq.port=
koroneiki.subscriber.rabbitmq.queuename=
koroneiki.subscriber.rabbitmq.ssl=
koroneiki.subscriber.rabbitmq.username=